version: '3.8'
services:
  tower:
    image: tailslideio/tower
    restart: always
    ports:
      - 3001:3001
    env_file: ./.env
    depends_on: 
      - nats
      - redis
      - postgres
    environment:
      - SDK_KEY=${SDK_KEY}
      - REACT_APP_SDK_KEY=${SDK_KEY}
  aerobat:
    image: tailslideio/aerobat
    env_file: ./.env
    restart: always
    depends_on: 
      - tower
      - nats
      - redis
    environment:
      - SDK_KEY=${SDK_KEY}
  nats:
    image: nats
    restart: always
    command: "-c /etc/nats/nats.conf --auth ${SDK_KEY}" 
    ports:
      - 4222:4222
      - 8080:8080
    volumes:
      - ./:/etc/nats
      - nats-data:/var/lib/nats/data/jetstream
  redis:
    image: redislabs/redistimeseries
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tower
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres-data:
    driver: local
  nats-data:
    driver: local
  redis-data:
    driver: local
